resources:
  - name: a_hello_changes_base
    type: GitRepo
    configuration:
      path: benanas-donuts/hello-changes
      gitProvider: stein321Github
      branches:
        include: master
      files:
        include: \ba\/base\/[A-Za-z/\.]+\b
  - name: a_hello_changes_version
    type: GitRepo
    configuration:
      path: benanas-donuts/hello-changes
      gitProvider: stein321Github
      branches:
        include: master
      files:
        include: \ba\/version\/[A-Za-z/\.]+\b
  - name: b_hello_changes_version
    type: GitRepo
    configuration:
      path: benanas-donuts/hello-changes
      gitProvider: stein321Github
      branches:
        include: master
      files:
        include: \bb\/version\/[A-Za-z/\.]+\b

pipelines:
  - name: hello_changes
    configuration:
      environmentVariables:
        readOnly:
          rtRegistry: "pipelines-docker"
          versionTag: "master"
          dockerRepo: "pipelines-docker.jfrog.io/jfrog"
          jfrogBuildNumber: "$run_id"
    steps:
      - name: runA
        type: Bash
        configuration:
          inputResources:
            - name: a_hello_changes_base
        execution:
          onStart:
            - curl ifconfig.me
            - cd $res_hello_changes_a_git_repo_resourcePath
            - ls
            - echo $jfrogBuildNumber
      - name: runB
        type: Bash
        configuration:
          integrations:
            - name: bsArt
          inputResources:
            - name: a_hello_changes_version
          inputSteps:
            - name: runA
        execution:
          onStart:
            - pushd $res_a_hello_changes_version_resourcePath
            - ls
            - cat a/version/bam.sh
            - popd
      - name: shouldFail
        type: Bash
        configuration:
          inputResources:
            - name: a_hello_changes_base
        execution:
          onStart:
            - docker --version
    - name: docker_build
      type: DockerBuild
      configuration:
        dockerFileLocation: "./d"
        dockerFileName: "Dockerfile"
        dockerImageName: "myalpine"
        dockerImageTag: latest
